/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125SignupRouteImport } from './routes/{-$locale}/signup'
import { Route as Char123LocaleChar125LoginRouteImport } from './routes/{-$locale}/login'
import { Route as Char123LocaleChar125authRouteRouteImport } from './routes/{-$locale}/(auth)/route'
import { Route as Char123LocaleChar125authDashboardLayoutRouteImport } from './routes/{-$locale}/(auth)/_dashboard-layout'
import { Route as Char123LocaleChar125authDashboardLayoutDashboardIndexRouteImport } from './routes/{-$locale}/(auth)/_dashboard-layout/dashboard/index'

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SignupRoute =
  Char123LocaleChar125SignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LoginRoute =
  Char123LocaleChar125LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authRouteRoute =
  Char123LocaleChar125authRouteRouteImport.update({
    id: '/(auth)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125authDashboardLayoutRoute =
  Char123LocaleChar125authDashboardLayoutRouteImport.update({
    id: '/_dashboard-layout',
    getParentRoute: () => Char123LocaleChar125authRouteRoute,
  } as any)
const Char123LocaleChar125authDashboardLayoutDashboardIndexRoute =
  Char123LocaleChar125authDashboardLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => Char123LocaleChar125authDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125authRouteRouteWithChildren
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/signup': typeof Char123LocaleChar125SignupRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/dashboard/': typeof Char123LocaleChar125authDashboardLayoutDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/signup': typeof Char123LocaleChar125SignupRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125authDashboardLayoutDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/(auth)': typeof Char123LocaleChar125authRouteRouteWithChildren
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/signup': typeof Char123LocaleChar125SignupRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/(auth)/_dashboard-layout': typeof Char123LocaleChar125authDashboardLayoutRouteWithChildren
  '/{-$locale}/(auth)/_dashboard-layout/dashboard/': typeof Char123LocaleChar125authDashboardLayoutDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/login'
    | '/{-$locale}/signup'
    | '/{-$locale}/'
    | '/{-$locale}/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/{-$locale}/login'
    | '/{-$locale}/signup'
    | '/{-$locale}/dashboard'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/(auth)'
    | '/{-$locale}/login'
    | '/{-$locale}/signup'
    | '/{-$locale}/'
    | '/{-$locale}/(auth)/_dashboard-layout'
    | '/{-$locale}/(auth)/_dashboard-layout/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/signup': {
      id: '/{-$locale}/signup'
      path: '/signup'
      fullPath: '/{-$locale}/signup'
      preLoaderRoute: typeof Char123LocaleChar125SignupRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/login': {
      id: '/{-$locale}/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125LoginRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(auth)': {
      id: '/{-$locale}/(auth)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125authRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(auth)/_dashboard-layout': {
      id: '/{-$locale}/(auth)/_dashboard-layout'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125authDashboardLayoutRouteImport
      parentRoute: typeof Char123LocaleChar125authRouteRoute
    }
    '/{-$locale}/(auth)/_dashboard-layout/dashboard/': {
      id: '/{-$locale}/(auth)/_dashboard-layout/dashboard/'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard/'
      preLoaderRoute: typeof Char123LocaleChar125authDashboardLayoutDashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125authDashboardLayoutRoute
    }
  }
}

interface Char123LocaleChar125authDashboardLayoutRouteChildren {
  Char123LocaleChar125authDashboardLayoutDashboardIndexRoute: typeof Char123LocaleChar125authDashboardLayoutDashboardIndexRoute
}

const Char123LocaleChar125authDashboardLayoutRouteChildren: Char123LocaleChar125authDashboardLayoutRouteChildren =
  {
    Char123LocaleChar125authDashboardLayoutDashboardIndexRoute:
      Char123LocaleChar125authDashboardLayoutDashboardIndexRoute,
  }

const Char123LocaleChar125authDashboardLayoutRouteWithChildren =
  Char123LocaleChar125authDashboardLayoutRoute._addFileChildren(
    Char123LocaleChar125authDashboardLayoutRouteChildren,
  )

interface Char123LocaleChar125authRouteRouteChildren {
  Char123LocaleChar125authDashboardLayoutRoute: typeof Char123LocaleChar125authDashboardLayoutRouteWithChildren
}

const Char123LocaleChar125authRouteRouteChildren: Char123LocaleChar125authRouteRouteChildren =
  {
    Char123LocaleChar125authDashboardLayoutRoute:
      Char123LocaleChar125authDashboardLayoutRouteWithChildren,
  }

const Char123LocaleChar125authRouteRouteWithChildren =
  Char123LocaleChar125authRouteRoute._addFileChildren(
    Char123LocaleChar125authRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125authRouteRoute: typeof Char123LocaleChar125authRouteRouteWithChildren
  Char123LocaleChar125LoginRoute: typeof Char123LocaleChar125LoginRoute
  Char123LocaleChar125SignupRoute: typeof Char123LocaleChar125SignupRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125authRouteRoute:
      Char123LocaleChar125authRouteRouteWithChildren,
    Char123LocaleChar125LoginRoute: Char123LocaleChar125LoginRoute,
    Char123LocaleChar125SignupRoute: Char123LocaleChar125SignupRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
